---
- name: "Disable firewall"
  service: name=firewalld state=stopped enabled=no
- name: "Disable SELinux"
  selinux:
    state: disabled
- name: "Touch /etc/NetworkManager/conf.d/99-no-dns.conf file"
  file:
    path: /etc/NetworkManager/conf.d/99-no-dns.conf
    state: touch
- name: "Explicitly instruct NetworkManager to never interact with your DNS configuration"
  blockinfile:
      path: /etc/NetworkManager/conf.d/99-no-dns.conf
      block: |
       [main]
       dns=none
      backup: yes
- name: "Restart NetworkManager"
  service: name=NetworkManager state=restarted
- name: "Disable systemd-logind"
  service: name=systemd-logind state=stopped enabled=no
- name: "Install the Yum repository configuration package for RHEL7"
  yum:
    name: https://packetfence.org/downloads/PacketFence/RHEL7/x86_64/RPMS/packetfence-release-1.2-7.el7.noarch.rpm
    state: present
- name: "Install PacketFence with all its dependencies, and the required external services (Database server, DHCP server, RADIUS server) "
  yum:
    name: packetfence
    enablerepo: packetfence
    state: latest
